package POS;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    Connection cn;
    PreparedStatement stat;
    ResultSet rs;

    public Login() {
        initComponents();
        aturFontTextField(); // baru setelah itu atur font
        setLocationRelativeTo(null); // tengah layar
        txt_username.requestFocusInWindow();
        cn = koneksi.BukaKoneksi();
    }

    class user {

        int id_user, id_level;
        String username, password, nama_user;

        public user(String username, char[] passwordChars) {
            this.username = username;
            this.password = new String(passwordChars); // aman
            this.nama_user = "";
            this.id_user = 0;
            this.id_level = 0;
        }
    }

    private void aturFontTextField() {
        Font fontBesar = new Font("Tahoma", Font.PLAIN, 20);
        txt_username.setFont(fontBesar);
        txt_password.setFont(fontBesar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        BGpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MASUK = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BGimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(275, 52));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BGpanel.setBackground(new java.awt.Color(255, 204, 102));
        BGpanel.setPreferredSize(new java.awt.Dimension(275, 300));
        BGpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 91, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login Account");
        BGpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 270, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        BGpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        BGpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 80, -1));

        MASUK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MASUK.setText("Login");
        MASUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MASUKActionPerformed(evt);
            }
        });
        BGpanel.add(MASUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 100, 30));
        BGpanel.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 270, 35));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        BGpanel.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 270, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 92, 153));
        jLabel3.setText("WELCOME BACK!");
        BGpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 92, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nice to See you Again");
        BGpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 300, 200, -1));

        BGimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/BG.png"))); // NOI18N
        BGimage.setText("Nice to See you Again");
        BGpanel.add(BGimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        jLabel1.setText("jLabel1");
        BGpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
        MASUKActionPerformed(evt);
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void MASUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MASUKActionPerformed
        // TODO add your handling code here:
        String username = txt_username.getText();
        char[] passwordChars = txt_password.getPassword();

        user u = new user(username, passwordChars);

        try {
            String sql = "SELECT * FROM user WHERE username = ? AND password = ?";
            stat = cn.prepareStatement(sql);
            stat.setString(1, u.username);
            stat.setString(2, u.password);
            rs = stat.executeQuery();

            if (rs.next()) {
                int id_level = rs.getInt("id_level");
                String nama_user = rs.getString("nama_user"); // ambil dari database

                // Simpan nama_user ke variabel global
                Session.namaUserLogin = nama_user;
                Session.idLevel = id_level;

                switch (id_level) {
                    case 1: // Administrator
                        new Customer(id_level).setVisible(true);
                        break;
                    case 2: // Kasir
                        new Transaksi(id_level).setVisible(true);
                        break;
                    case 3: // Logistik
                        new Operasional(id_level).setVisible(true);
                        break;
                }
                this.dispose(); // tutup login

            } else {
                JOptionPane.showMessageDialog(this, "Username atau password salah");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        } finally {
            java.util.Arrays.fill(passwordChars, '0');
        }
    }//GEN-LAST:event_MASUKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGimage;
    private javax.swing.JPanel BGpanel;
    private javax.swing.JButton MASUK;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
